// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce_app/test/features/product/presentation/bloc/product-bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ecommerce_app/core/error/failures.dart' as _i6;
import 'package:ecommerce_app/core/usecases/usecase.dart' as _i8;
import 'package:ecommerce_app/features/product/domain/entities/product.dart'
    as _i7;
import 'package:ecommerce_app/features/product/domain/repositories/product_repository.dart'
    as _i2;
import 'package:ecommerce_app/features/product/domain/usecases/create_product.dart'
    as _i10;
import 'package:ecommerce_app/features/product/domain/usecases/delete_product.dart'
    as _i12;
import 'package:ecommerce_app/features/product/domain/usecases/update_product.dart'
    as _i11;
import 'package:ecommerce_app/features/product/domain/usecases/view_all_products.dart'
    as _i4;
import 'package:ecommerce_app/features/product/domain/usecases/view_product.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductRepository_0 extends _i1.SmartFake
    implements _i2.ProductRepository {
  _FakeProductRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ViewAllProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewAllProducts extends _i1.Mock implements _i4.ViewAllProducts {
  @override
  _i2.ProductRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, List<_i7.Product>>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failures, List<_i7.Product>>>.value(
                  _FakeEither_1<_i6.Failures, List<_i7.Product>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failures, List<_i7.Product>>>.value(
                  _FakeEither_1<_i6.Failures, List<_i7.Product>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failures, List<_i7.Product>>>);
}

/// A class which mocks [ViewProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewProductUseCase extends _i1.Mock
    implements _i9.ViewProductUseCase {
  @override
  _i2.ProductRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, _i7.Product>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failures, _i7.Product>>.value(
                  _FakeEither_1<_i6.Failures, _i7.Product>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failures, _i7.Product>>.value(
                  _FakeEither_1<_i6.Failures, _i7.Product>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failures, _i7.Product>>);
}

/// A class which mocks [CreateProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateProductUseCase extends _i1.Mock
    implements _i10.CreateProductUseCase {
  @override
  _i2.ProductRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> call(_i7.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#call, [product]),
            returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
              _FakeEither_1<_i6.Failures, void>(
                this,
                Invocation.method(#call, [product]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                  _FakeEither_1<_i6.Failures, void>(
                    this,
                    Invocation.method(#call, [product]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failures, void>>);
}

/// A class which mocks [UpdateProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProductUseCase extends _i1.Mock
    implements _i11.UpdateProductUseCase {
  @override
  _i2.ProductRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> call(_i7.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#call, [product]),
            returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
              _FakeEither_1<_i6.Failures, void>(
                this,
                Invocation.method(#call, [product]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                  _FakeEither_1<_i6.Failures, void>(
                    this,
                    Invocation.method(#call, [product]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failures, void>>);
}

/// A class which mocks [DeleteProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductUseCase extends _i1.Mock
    implements _i12.DeleteProductUseCase {
  @override
  _i2.ProductRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
              _FakeEither_1<_i6.Failures, void>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                  _FakeEither_1<_i6.Failures, void>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failures, void>>);
}
